

# This file was *autogenerated* from the file stereotyped_message_attack.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_2048 = Integer(2048)
from Crypto.Util.number import *


class RSA:
    def __init__(self, bits):
        assert bits % _sage_const_2  == _sage_const_0 
        self.gen_new_key(bits)
    
    def gen_new_key(self, bits):
        self.p = getPrime(bits // _sage_const_2 )
        self.q = getPrime(bits // _sage_const_2 )
        self.N = self.p * self.q
        self.e = _sage_const_3 
        phi = (self.p - _sage_const_1 ) * (self.q - _sage_const_1 )
        self.d = inverse(self.e, phi)

    def encryption(self, m):
        if isinstance(m, str):
            m = bytes_to_long(m.encode("utf-8"))
        if isinstance(m, bytes):
            m = bytes_to_long(m)
        c = pow(m, self.e, self.N)
        return c

    def decryption(self, c):
        m = pow(c, self.d, self.N)
        m = long_to_bytes(m)
        return m
    
    def stereotyped_message_attack(self, prefix, c):
        PR = PolynomialRing(Zmod(self.N), names=('x',)); (x,) = PR._first_ngens(1)
        f = (prefix + x)**self.e - c
        diff = f.small_roots()
        if len(diff):
            return long_to_bytes(int(diff[_sage_const_0 ]))
        else:
            return "not found..."


m = b"stereotyped_message_attack!!!"
prefix = b"Hello..."
m = bytes_to_long(m)
prefix = bytes_to_long(prefix) << (m.bit_length() + _sage_const_1 )

m += prefix

r = RSA(_sage_const_2048 )

print(long_to_bytes(m))
cipher = r.encryption(m)
plane = r.decryption(cipher)

print("-*-*-*-*-*-*-*-*-*-*-")
print(r.stereotyped_message_attack(prefix, cipher))
print("-*-*-*-*-*-*-*-*-*-*-")


